DROP TABLE IF EXISTS STILLS;  
DROP TABLE IF EXISTS SOUNDEFFECTS;
DROP TABLE IF EXISTS MOVIES;

CREATE TABLE STILLS(  
stills_code INT AUTO_INCREMENT PRIMARY KEY,
movie_stillsId VARCHAR(10) NOT NULL,  
movie_stills VARCHAR(512)
);

CREATE TABLE SOUNDEFFECTS(  
se_code INT AUTO_INCREMENT  PRIMARY KEY, 
movie_soundId VARCHAR(10) NOT NULL,  
movie_sounds VARCHAR(100) NOT NULL 
);

CREATE TABLE MOVIES(  
movie_code INT AUTO_INCREMENT PRIMARY KEY,
movie_title VARCHAR(100) NOT NULL,
movie_language VARCHAR(30) NOT NULL,
movie_location VARCHAR(30) NOT NULL,
movie_plot VARCHAR(2000) NOT NULL,
movie_posterUrl VARCHAR(512) NOT NULL,
movie_soundId VARCHAR(10) NOT NULL,
movie_stillsId VARCHAR(10) NOT NULL,
movie_imdbID VARCHAR(15) NOT NULL,
movie_listingType VARCHAR(50) NOT NULL,
movie_imdbRating VARCHAR(10) NOT NULL
);